services:
  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_app_tier
    networks:
      - my-network 
    ports:
      - 8080:8080
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://user:pass@mongo:27017/mydatabase # <-- This is needed
      PORT: 8080 # <-- Match the port mapping

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_presentation_tier
    networks:
      - my-network 
    ports:
      - 8000:8000
    depends_on:
      - api-server

  mongo:
    image: mongo:4.4
    container_name: cont-mongodb
    ports:
      - 27017:27017
    networks:
      - my-network 
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand({ping: 1})" ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s # Wait 10 seconds before starting checks


  mongo-express:
    image: mongo-express
    container_name: mon-expr-cont
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    networks:
      - my-network
    depends_on:
      mongo:
        condition: service_healthy

networks:
  my-network:
    driver: bridge
