version: '3.8'

services:
  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_app_tier
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_presentation_tier
    ports:
      - "8000:8000"
    depends_on:
      - api-server

