services:
  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_app_tier
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "mongodb"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_presentation_tier
    ports:
      - "8000:8000"
    depends_on:
      - api-server

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports:
      - "9000:9000"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    depends_on:
      - "mongodb"
